data:
  name: celeba
  root: ~/data/CelebA/
  img_size: 64

dataloader:
  num_workers: 4
  pin_memory: true
  prefetch_factor: 2


prior:
  target: models.prior.transformer.Transformer
  params:
    codebook_num: 512
    embed_dim: 512
    n_heads: 8
    n_layers: 12
    max_tokens: 256


vqmodel:
  downsample_factor: 4

  z_channels: 256
  codebook_num: 512
  codebook_dim: 64

  encoder:
    target: models.autoencoder.net.Encoder
    params:
      img_channels: 3
      hidden_dim: 256
      n_resblocks: 2

  decoder:
    target: models.autoencoder.net.Decoder
    params:
      img_channels: 3
      hidden_dim: 256
      n_resblocks: 2

  quantizer:
    target: models.quantizer.VectorQuantizerEMA
    params:
      codebook_num: 512
      codebook_dim: 64
      ema_decay: 0.99
